apiVersion: v1
kind: Service
metadata:
  name: user-microservice
  labels:
    service: user-microservice
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: user-microservice